#!/bin/sh

# Simple tests that do not require any external tools: i.e.
# these just setup little fake working copies and make sure
# that vcprompt does the right thing in them.

. ./common.sh

test_no_vc()
{
    cd $tmpdir
    mkdir novc && cd novc
    assert_vcprompt "no vc 1" ""
    assert_vcprompt "no vc 2" "" "%n:%b"
}

test_root()
{
    cd /
    assert_vcprompt "root dir" ""
}

test_simple_git()
{
    cd $tmpdir
    mkdir git && cd git
    mkdir .git

    assert_vcprompt "git broken 1" ""
    assert_vcprompt "git broken 2" "" "%n:%b"

    echo 3f786850e387550fdab836ed7e6dc881de23001b > .git/HEAD
    assert_vcprompt "git nobranch" "(unknown)"
    assert_vcprompt "git nobranch (show rev)" "(unknown):3f786850e387" "%b:%r"

    echo "ref: refs/heads/foo" > .git/HEAD
    assert_vcprompt "git branch" "git:foo" "%n:%b"

    mkdir -p .git/refs/heads
    echo ffca1632148005094dc0d491aa19f8ba7f68b81c > .git/refs/heads/foo
    assert_vcprompt "git branch and rev" "foo:ffca16321480" "%b:%r"

    mkdir subdir && cd subdir
    assert_vcprompt "git subdir" "foo"
}

test_bad_dir()
{
    cd $tmpdir
    set -e
    mkdir -p d1/d2
    cd d1/d2
    chmod a-rx ..
    assert_vcprompt "bad dir" ""
    chmod a+rx ..
}

test_env_var()
{
    cd $tmpdir

    mkdir env_var && cd env_var
    mkdir .git
    echo "ref: refs/heads/foo" > .git/HEAD

    VCPROMPT_FORMAT='foo:%n' assert_vcprompt 'env var' 'foo:git' '-'
    VCPROMPT_FORMAT='foo:%n' assert_vcprompt 'env var override' 'bar:git' 'bar:%n'
}

test_help()
{
    cd $tmpdir

    if $vcprompt -h > /dev/null; then
        echo "fail: help exit status: expected non-zero" >&2
        failed="y"
    else
        echo "pass: help exit status"
    fi

    for pat in '%b' '%r' '%u' '%m' '%n' '%%'; do
        if ! $vcprompt -h | grep "$pat" > /dev/null; then
            echo "fail: help text should contain '$pat'" >&2
            failed="y"
        fi
    done
    echo "pass: help text"
}

#set -e

find_vcprompt
setup

failed=""

test_no_vc
test_root
test_simple_git
test_bad_dir
test_env_var
test_help

report
